server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:NETFLIX}
    username: ${DB_USERNAME:netflix}
    password: ${DB_PASSWORD:netflix}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

  cloud:
    gateway:
      httpclient:
        pool:
          maxIdleTime: 10000

#  # need to add @EnableCaching to configuration if application.yaml config is used instead of CachingConfig file
#  cache:
#    cache-names: trendingTitles
#    caffeine.spec: expireAfterAccess=6s
